import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import '@/app/globals.css';

type RootLayoutProps = {
  children: JSX.Element;
};

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Passkeys with Next.js',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={`min-h-screen flex flex-col gap-4 justify-center items-center ${inter.className}`}>
        <header>
          <h1 className="font-bold text-xl text-center">next-passkeys</h1>
        </header>
        <main className="flex flex-col gap-4">{children}</main>
        <footer>
          <nav>
            <ul className="flex gap-4 [&_a]:underline">
              <li>
                <Link href="/">Index</Link>
              </li>
              <li>
                <Link href="/home">Home</Link>
              </li>
              <li>
                <Link href="/login">Login</Link>
              </li>
            </ul>
          </nav>
        </footer>
      </body>
    </html>
  );
}
